
CREATE DATABASE IF NOT EXISTS vendinha;
USE vendinha;


CREATE TABLE itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    produto VARCHAR(255) NOT NULL,  
    categoria VARCHAR(50) NOT NULL,
    peso VARCHAR(20) NOT NULL
);